- name: Setup Whitelabel themes
  hosts: all
  become: True
  gather_facts: True
  vars_files:
    - "roles/edxapp/defaults/main.yml"
    - "roles/discovery/defaults/main.yml"
    - "roles/ecommerce/defaults/main.yml"
  roles:
    - whitelabel
