WHITELABEL_MYSQL_COMMANDS:
  - "CREATE SCHEMA discovery;"
  - "CREATE USER 'discov001'@'localhost' IDENTIFIED BY 'password';"
  - "GRANT ALL PRIVILEGES ON discovery.* TO 'discov001'@'localhost';"

WHITELABEL_THEME_DIR: "edx-themes"

discovery_code_dir: "{{ discovery_home }}/{{ discovery_service_name }}"
