- name: "display compile assets command"
  debug:
    msg: "{{ COMMON_BIN_DIR }}/edxapp-update-assets-{{ item }}"
  with_items: "{{ service_variants_enabled }}"

- name: "display Sites and Themes command"
  debug:
    msg: "{{ COMMON_BIN_DIR }}/python.edxapp {{ COMMON_BIN_DIR }}/manage.edxapp lms --settings={{ COMMON_EDXAPP_SETTINGS }}
    create_sites_and_configurations --dns-name {{ dns_name }} --theme-path {{ WHITELABEL_THEME_DIR }}"
  with_items: "{{ service_variants_enabled }}"

- name: Create Sites and Themes
  shell: >
    {{ COMMON_BIN_DIR }}/python.edxapp {{ COMMON_BIN_DIR }}/manage.edxapp lms --settings={{ COMMON_EDXAPP_SETTINGS }}
    create_sites_and_configurations --dns-name {{ dns_name }} --theme-path {{ WHITELABEL_THEME_DIR }}
  become_user: "{{ edxapp_user }}"
  environment: "{{ edxapp_environment }}"

# Discovery Setup

#- name: Uninstall installed version of elasticsearch
#  become: True
#  shell: >
#    apt-get -y remove elasticsearch
#
#- name: Install latest version of elasticsearch.
#  become: True
#  shell: >
#    apt-get -y install elasticsearch
#    systemctl enable elasticsearch.service
#

- name: Run discovery playbook
  become: True
  shell: >
    /edx/app/edx_ansible/venvs/edx_ansible/bin/ansible-playbook -i localhost, -c local -e@/edx/app/edx_ansible/server-vars.yml /edx/app/edx_ansible/edx_ansible/playbooks/edx-east/discovery.yml

- name: Setup MySql Database
  shell: 'mysql -u root -e "{{ item }}"'
  with_items: "{{ WHITELABEL_MYSQL_COMMANDS }}"

- name: Run Discovery migrations
  shell: ". {{ discovery_home }}/discovery_env && make migrate"
  args:
    chdir: "{{ discovery_code_dir }}"
  become_user: "{{ discovery_user }}"

#- name: "Checkout code"
#  git:
#    repo: 'https://github.com/edx/course-discovery.git'
#    dest: /edx/app/discovery/discovery
#    version: hasnain-naveed/management_command/WL-1295

#  environment: "{{ discovery_environment }}"

- name: Create Sites and Partners
  shell: >
   {{ COMMON_BIN_DIR }}/python.discovery {{ COMMON_BIN_DIR }}/manage.discovery
   create_sites_and_partners --dns-name {{ dns_name }} --settings=course_discovery.settings.production --theme-path {{ WHITELABEL_THEME_DIR }}
  become_user: "{{ discovery_user }}"
  environment: "{{ discovery_environment }}"

- name: Print Env
  shell: printenv
  become_user: "{{ discovery_user }}"
  environment: "{{ discovery_environment }}"
